# Generated by Django 3.2.4 on 2021-07-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210715_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='experiences',
            new_name='experience',
        ),
    ]
