# Generated by Django 3.2.4 on 2021-07-15 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210715_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.course'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='experience',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.experience'),
        ),
    ]
