# Generated by Django 3.2.4 on 2021-07-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210715_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='course',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='experience',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
