# Generated by Django 3.2.4 on 2021-07-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210715_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='education',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='github',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='work',
        ),
    ]
