# Generated by Django 3.2.4 on 2021-07-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210715_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
