from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('add-board/', views.add_board, name='add_board'),
    path('add-badge/', views.add_badge, name='add_badge'),
    path('settings/', views.settings, name='settings'),
    path('about/', views.about, name='about'),
    path('base/', views.base, name='base'),
    path('badges/', views.badges, name='badges'),
    path('reported-topics/', views.reported_topics, name='reported_topics'),
    path('reported-users/', views.reported_users, name='reported_users'),
    path('view-reported-topic/<int:topic_id>/', views.view_reported_topic, name='view_reported_topic'),
    path('reported-topics/seen', views.seen_reported_topics, name='seen_reported_topics'),
    path('reported-topics/unseen', views.unseen_reported_topics, name='unseen_reported_topics'),
    path('reported-topics/<int:reported_topic_id>/reported-topic', views.reported_topic, name='reported_topic'),
    path('reported-topics/<int:reported_topic_id>/block-topic', views.block_topic, name='block_topic'),
    path('reported-topics/<int:reported_topic_id>/unblock-topic', views.unblock_topic, name='unblock_topic'),
    path('delete-user/', views.delete_user, name='delete_user'),
    path('block-user/<int:user_id>/', views.block_user, name='block_user'),
    path('badges/<int:badge_id>/delete-badge', views.delete_badge, name='delete_badge'),
    path('badges/<int:badge_id>/edit-badge', views.edit_badge, name='edit_badge'),
    path('boards/<int:board_id>/', views.board_topics, name='board_topics'),
    path('boards/<int:board_id>/delete-board', views.delete_board, name='delete_board'),
    path('boards/<int:board_id>/edit-board', views.edit_board, name='edit_board'),
    path('boards/search/', views.topics_search, name='topics_search'),
    path('boards/<int:board_id>/tags/<int:tag_id>', views.filter_topics, name='filter_topics'),
    path('boards/new-topic/', views.new_topic, name='new_topic'),
    path('boards/<int:board_id>/topics/<int:topic_id>', views.topic_content, name='topic_content'),
    path('boards/<int:board_id>/topics/<int:topic_id>/report', views.report_topic, name='report_topic'),
    path('profile/<int:user_id>/', views.user_profile, name='user_profile'),
    path('profile/<int:user_id>/report', views.report_user, name='report_user'),
    path('badge/<int:badge_id>/', views.badge, name='badge'),
    path('boards/<int:board_id>/topics/<int:topic_id>/like/', views.like_topic, name='like_topic'),
    path('boards/<int:board_id>/topics/<int:topic_id>/delete-topic/', views.delete_topic, name='delete_topic'),
    path('boards/<int:board_id>/topics/<int:topic_id>/edit-topic/', views.edit_topic, name='edit_topic'),
    path('boards/<int:board_id>/topics/<int:topic_id>/filtred-topics', views.filter_topic_content, name='filter_topic_content'),
    path('boards/<int:board_id>/topics/<int:topic_id>/<int:post_id>/delete/', views.delete_comment, name='delete_comment'),
    path('boards/<int:board_id>/topics/<int:topic_id>/<int:post_id>/edit/', views.edit_comment, name='edit_comment'),
]