# Generated by Django 3.2.4 on 2021-08-03 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0005_alter_like_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Harassment', 'Harassment'), ('Terrorism', 'Terrorism'), ('False information', 'False information'), ('Something else', 'Something else'), ('Nudity', 'Nudity'), ('Suicide or self-injury', 'Suicide or self-injury'), ('Violence', 'Violence'), ('Spam', 'Spam')], max_length=100)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_from_user', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_topic', to='boards.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
