# Generated by Django 3.2.4 on 2021-08-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_report_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report_topic',
            name='report_type',
            field=models.CharField(choices=[('Suicide or self-injury', 'Suicide or self-injury'), ('Terrorism', 'Terrorism'), ('Violence', 'Violence'), ('Something else', 'Something else'), ('Harassment', 'Harassment'), ('Nudity', 'Nudity'), ('False information', 'False information'), ('Spam', 'Spam')], max_length=100),
        ),
    ]
