# Generated by Django 3.2.4 on 2021-08-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20210804_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='is_reported',
            new_name='is_blocked',
        ),
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10),
        ),
        migrations.AlterField(
            model_name='report_topic',
            name='report_type',
            field=models.CharField(choices=[('Nudity', 'Nudity'), ('Suicide or self-injury', 'Suicide or self-injury'), ('Something else', 'Something else'), ('Spam', 'Spam'), ('Violence', 'Violence'), ('Terrorism', 'Terrorism'), ('False information', 'False information'), ('Harassment', 'Harassment')], max_length=100),
        ),
    ]
