# Generated by Django 3.2.4 on 2021-08-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20210804_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Unlike', 'Unlike'), ('Like', 'Like')], default='Like', max_length=10),
        ),
        migrations.AlterField(
            model_name='report_topic',
            name='report_type',
            field=models.CharField(choices=[('Spam', 'Spam'), ('Nudity', 'Nudity'), ('Harassment', 'Harassment'), ('Terrorism', 'Terrorism'), ('Something else', 'Something else'), ('False information', 'False information'), ('Suicide or self-injury', 'Suicide or self-injury'), ('Violence', 'Violence')], max_length=100),
        ),
    ]
